version: '3.8'
services:
  service:
    container_name: service
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    volumes:
    - .:/usr/src/app

  database:
    container_name: database
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - db-data:/data/database
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
 db-data:
